version: '3.6'

services:
  nginx:
    build: ./docker/nginx
    ports:
      - ${NGINX_HOST_PORT}:80
    volumes:
      - ${PWD}/api/.:/app
    networks:
      - tutor-network

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql-vol:/var/lib/mysql
    ports:
      - ${MYSQL_HOST_PORT}:${DB_PORT}
    networks:
      - tutor-network

  redis:
    image: redis:5.0.0-alpine
    restart: always
    volumes:
      - redis-vol:/data
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_PORT}
    networks:
      - tutor-network

  api:
    build:
      context: ./docker/api
      args:
        DOCKER_UID: ${DOCKER_UID:-0}
        DOCKER_GID: ${DOCKER_GID:-0}
    tty: true
    stdin_open: true
    command: sh /docker-entrypoint.sh
    volumes:
      - ${PWD}/api/.:/app
    networks:
      - tutor-network

  client:
    tty: true
    stdin_open: true
    restart: always
    command: sh /docker-entrypoint.sh
    build:
      context: ./docker/client
      args:
        ENVIROMENT: ${ENVIROMENT:-DEV}
    ports:
      - ${CLIENT_HOST_PORT}:3000
    environment:
      HOST: 0.0.0.0
    volumes:
      - ${PWD}/client/.:/app
    networks:
      - tutor-network

volumes:
  mysql-vol:
    driver: local
  redis-vol:
    driver: local

networks:
  tutor-network:
    driver: bridge
